// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "extensions.zotero.sidebarChat.apiBase": string;
      "extensions.zotero.sidebarChat.model": string;
      "extensions.zotero.sidebarChat.apiKey": string;
      "extensions.zotero.sidebarChat.contextMaxPromptTokens": string;
      "extensions.zotero.sidebarChat.contextRecentTurns": string;
    };
  }
}
