// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "extensions.zotero.geminiChat.apiBase": string;
      "extensions.zotero.geminiChat.model": string;
      "extensions.zotero.geminiChat.apiKey": string;
    };
  }
}
